version: '2'
services:
  web:
    mem_limit: 2500m
    image: spydertrap/docker:apache
    ports:
      - "8000"
    volumes:
      - .:/var/www/web
    external_links:
      - "mysql"
    environment:
      VIRTUAL_HOST: wedding.dev
      WEBROOT: /var/www/web/public
networks:
  default:
    external:
      name: nginx-proxy
